# Generated by Django 3.0.7 on 2020-07-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_transactions', '0001_initial'),
        ('transactions', '0001_initial'),
        ('credit_cwallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Not Payed'), (1, 'Payed')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_cwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credit_cwallet', to='credit_cwallets.CreditCwallet')),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_transactions.CreditTransaction')),
            ],
            options={
                'db_table': 'debt',
            },
        ),
        migrations.CreateModel(
            name='DebtHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt_credit_cwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_transaction', to='debts.Debt')),
                ('repayment_debt_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.TransactionRegular')),
            ],
            options={
                'db_table': 'debt_history',
            },
        ),
    ]
