# Generated by Django 3.0.7 on 2020-07-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_debt_debt_repayment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debt',
            old_name='debt_repayment_time',
            new_name='repayment_date_time',
        ),
    ]
