# Generated by Django 3.0.7 on 2020-07-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_cwallets', '0001_initial'),
        ('credit_marketers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCommissionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Percentage'), (1, 'Fixed Amount')], default=0)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cwallets.CreditCwallet')),
                ('credit_marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_marketers.CreditMarketer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_receiver', to='credit_cwallets.CreditCwallet')),
            ],
            options={
                'db_table': 'credit_commission_setting',
                'unique_together': {('credit_marketer', 'receiver', 'club')},
            },
        ),
    ]
