# Generated by Django 3.0.7 on 2020-07-08 17:16

import credit_card.credit_marketers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cwallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditMarketer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_img', models.ImageField(upload_to=credit_card.credit_marketers.models.CreditMarketer.contract_upload_path)),
                ('bank_guarantee', models.ImageField(blank=True, null=True, upload_to=credit_card.credit_marketers.models.CreditMarketer.bank_guarantee_path)),
                ('financing_tracking_code', models.CharField(blank=True, max_length=20, null=True)),
                ('credit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=13)),
                ('transaction_amount_remain', models.DecimalField(decimal_places=0, default=0, max_digits=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer_cwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cwallets.CWalletRegular')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_marketers.Organization')),
            ],
            options={
                'db_table': 'credit_marketer',
            },
        ),
    ]
