# Generated by Django 3.0.7 on 2020-07-18 16:19

import credit_card.credit_marketers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_marketers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditmarketer',
            name='contract_img',
            field=models.ImageField(blank=True, null=True, upload_to=credit_card.credit_marketers.models.CreditMarketer.contract_upload_path),
        ),
    ]
