# Generated by Django 3.0.7 on 2020-07-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit_transactions', '0001_initial'),
        ('credit_cwallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_datetime', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Done'), (2, 'Cancel'), (3, 'Rejected')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_cwallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_cwallets.CreditCwallet')),
                ('credit_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_transactions.CreditTransaction')),
            ],
            options={
                'db_table': 'demand',
            },
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=9)),
                ('status', models.IntegerField(choices=[(0, 'Pay To Club'), (1, 'Withdraw'), (2, 'Shopping'), (3, 'Pay for Commission')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demands.Demand')),
            ],
            options={
                'db_table': 'demand_history',
            },
        ),
    ]
